### ISSUE TITLE
using OnPlatform with maui:OnScreenSize  what is the way to do it

### ISSUE THREAD

**Issue by gabsamples6** [carolzbnbr/OnScreenSizeMarkup#11]
Hi 
Not sure if this is a bug or not supported or cannot be done or I am doing all wrong :)

In my app I have a FontStyles.xaml  resourcedictionary and I tried to do 

			<OnPlatform x:Key="DefaultFontIconSize" x:TypeArguments="x:Double">
				<OnPlatform.Platforms>
					<On Platform="Android">
						<maui:OnScreenSize
							Default="25"
							ExtraSmall="16"
							Large="40"
							Medium="30"
							Small="20" />
					</On>
					<On Platform="iOS">
						<maui:OnScreenSize
							Default="25"
							ExtraSmall="16"
							Large="40"
							Medium="30"
							Small="20" />
					</On>
				</OnPlatform.Platforms>
			</OnPlatform>

But I get this

**An error occurred: 'Não foi posivel determinar a propriedade para fornecer o valor.**'. Callstack: '   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.ProvideValue(Object& value, ElementNode node, Object source, XmlName propertyName)
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ElementNode node, INode parentNode)
etc....

My question is the above possible?
thanks

**Comment by carolzbnbr** [comment]
Hey, Hi!! 

Well, its kind of strange that exception, on my machine I have a similar code and that works perfectly.
I kind of hate this type of reply, but it is working on my machine", as you can see by looking at [this](https://carolshomelab.quickconnect.to/d/s/sP2ZX1hUQw2a4YXxTt2Iq6trAyHfAD40/dYO_vAAjQm_SNVSbfpScSkjFiNqRQiXT-hLUgBtd3OAo) video.

That exception belongs to the library's code, but in that case it should work without raising the exception.

Maybe is something else.

**Comment by carolzbnbr** [comment]
Maybe if you could share a small project reproducing the issue and send me the link, so I can try to reproduce your problem here.

**Comment by gabsamples6** [comment]
Hi 
Link to a small project here 
https://github.com/gabsamples6/SampleFontSizes


1. Visual studio 2022 
2. Created a new Maui Project
3. Added the  below snippet to Resources/Styles/Styles.xaml

         <OnPlatform x:Key="DefaultFontIconSize" x:TypeArguments="x:Double">
              <OnPlatform.Platforms>
                  <On Platform="Android">
                      <markup:OnScreenSize
                          Default="25"
                          ExtraSmall="16"
                          Large="40"
                          Medium="30"
                          Small="20" />
                  </On>
                  <On Platform="iOS">
                      <markup:OnScreenSize
                          Default="25"
                          ExtraSmall="16"
                          Large="40"
                          Medium="30"
                          Small="20" />
                  </On>
              </OnPlatform.Platforms>
          </OnPlatform>

   4. Builds successfully
   5. Run android and crashes!!
   
I even tried to change the Double quotes to single but Visual studio when saving converts them to double quotes..

Have I got something wrong in the syntax?
I hope is not a maui bug otherwise it will never be fixed!!

thanks

**Comment by carolzbnbr** [comment]
I have tested your sample project and I was able to reproduce it on both iOS/Android (simulators). 

For some reason when you use the library the way you are using (inside OnPlatform tags without Style's tag, andl **also** inside a Styles.xaml file) it doesn't seem to work.

BUT if you move your code to a LayoutPage (ContentPage, for instance) it works. 

Unfortunately, It seems to me that Maui does not recognize the markup elements when you use it the way you are using.

It's not a bug of the library itself, otherwise if we moved the code from the Styles.xaml file to a contentPage it should also not work.

The only workaround I can think of by now is moving your code to a contentPage.

**Comment by gabsamples6** [comment]
Thanks for your prompt reply. In our projects we use styles like - FontStyles - ButtonStyles etc...  basically all the generic styles are there ..  Its a pain because we dont want to have that code scattered everywhere.... I will look for a workaround. 
I would be happy to report it as bug but its so demotivating at the moment as nothing is getting fixed ...  and I totally get it is not a issue with your library. Will close now but what a pain in the...

**Comment by carolzbnbr** [comment]
Hi,

just published a new nuget that probably addressed your issue.

All you have to do is specify the type you want the markup to apply, by defining the FallbackType.

like this:

```cs

         <OnPlatform x:Key="ImageSize" x:TypeArguments="x:Double">
               <OnPlatform.Platforms>
                   <On Platform="Android">
                       <markups:OnScreenSize FallbackType="{x:Type x:Double}"
                           Default="70"
                           Medium="130"
                           Large="170"
                           ExtraLarge="350" />
                   </On>
                   <On Platform="iOS">
                       <markups:OnScreenSize FallbackType="{x:Type x:Double}"
                           Default="80"
                           Medium="150"
                           Large="200"
                           ExtraLarge="300"
                           />
                   </On>
               </OnPlatform.Platforms>
           </OnPlatform>
```


Hope this helps.

**Comment by gabsamples6** [comment]
Hey just seen this, I will have a go and let you know Brilliant!!! thanks for letting me know.
