### ISSUE TITLE
Xamarin Fail to classify this device screen size based on Width/Height

### ISSUE THREAD

**Issue by gabsamples6** [carolzbnbr/OnScreenSizeMarkup#15]
Hi

I dont think this is a bug but more how we should handle on our side and get some advice from you .
We noticed that we get lot of crashes with this info in AppCenter (this is a xamarin app)

_**_System.TypeInitializationException: Fail to classify this device screen size based on Width/Height (1440x3216). Maybe you need to implement your own version of the handler._**_

I have been through the code and we always have a defaultsize.

We dont want the app to crash/hang etc.. and seems to happen with Oppo phones and we dont have one to test on.. 

do you need to thrown an Error in your ScreenCategoryextension.GetHandlerCategory? Surely could return a default instead of the exception .. what do you think?

or in Xamarin how do I add another an additinal screensize 

        private static ScreenSizeInfo[] screenSizeCategories = new ScreenSizeInfo[]
         {                     
            new ScreenSizeInfo(1440,3216, ScreenCategories.ExtraLarge),
        };

Any advice welcome!

thanks again for this control.

**Comment by carolzbnbr** [comment]
Hello,

I should clarify upfront that this Xamarin Forms library is outdated, and I currently don't have plans for further updates or support.

However, I'm still happy to offer some guidance.

The Xamarin library utilizes a significantly different approach compared to its .NET MAUI counterpart. In Xamarin, we use a concept I've coined as a "CategoryFallbackHandler", which shouldn't be mistaken for Xamarin's UI Custom Renderers or MAUI handlers.

A 'Handler' in this context is a class implementing the `ICategoryFallbackHandler` interface. Its role is to categorize the screen size (large, small, extra-small, etc.), based on either the device model or screen dimensions.

Considering that categorization by screen size can occasionally yield unexpected results, our first attempt is to categorize the screen by the device model using the `TryGetCategoryByDeviceModel` method. If unsuccessful, we then resort to the `TryGetCategoryByPhysicalSize` method.

The default implementation of the `ICategoryFallbackHandler` is the [DefaultCategoryFallbackHandler](https://github.com/carolzbnbr/OnScreenSizeMarkup/blob/main/src/OnScreenSizeMarkup/OnScreenSizeMarkup.Core/DefaultCategoryFallbackHandler.cs). If you're encountering issues, you may find it helpful to add an additional dictionary entry for your specific device.

After you've prepared your custom CategoryFallbackHandler implementation, you can set it up with the following command:

```csharp
OnScreenSizeMarkup.Core.Manager.Handler = new YourCategoryFallbackHandlerClass();
```

Please remember, as I mentioned before, the Xamarin version of this library doesn't have the robustness of its MAUI equivalent, and it doesn't quite live up to my personal expectations.

Hope this helps.

**Comment by gabsamples6** [comment]
Hi,
thank you so much for your prompt reply, we are migrating to Maui and using the Maui version too but because of all the issues Maui has  it has delayed our Maui launch and therefore we still have xamarin live unfortunately.. I am sure you are well aware of what is going on in Maui and all the discontent around it.

I have just done exactly what you suggested but I am not sure if my CustomScreenSizeFallbackHandler will override the internal one or just add to it, I have just copied the content of the defaultHandler and added an extra row .
Unnecessary may be but I didnt know better :) .

What about if I use the actual source and nuke that exception to prevent future crashes, I know up to me but and suggestions would be appreciated.

```
  Manager.Current.Handler = new CustomScreenSizeFallbackHandler(); 
//inside the  CustomScreenSizeFallbackHandler I added this 
new ScreenSizeInfo(1440,3216, ScreenCategories.ExtraLarge),
```

thanks again,  and for MAUI shall I just do below  how Can I speficify "1440x3216"

            OnScreenSizeMarkup.Maui.Manager.Current.Mappings.Add(new SizeMappingInfo(??? , ScreenCategories.Large,
                ScreenSizeCompareModes.SpecificSize));

Many thanks again

**Comment by carolzbnbr** [comment]
Hi,

I believe the Xamarin approach will work. 

For .NET MAUI, you can use a similar approach as you shwon above, but maybe with a few tweaks...

For the `???` part in the snippet you shared, you would need to fill in the screen's diagonal size for the device you are working with. You can usually find this information on the device vendor's website.

If you specify `ScreenSizeCompareModes.SmallerOrEqualsTo` instead of `ScreenSizeCompareModes.SpecificSize`, you're instructing the library that any diagonal size between the largest pre existing sizes on  ``OnScreenSizeMarkup.Maui.Manager.Current.Mappings`` and your new size will be categorized as Large.

Here's the adapted code:

```csharp
OnScreenSizeMarkup.Maui.Manager.Current.Mappings.Add(new SizeMappingInfo(DIAGONAL_SIZE_HERE, ScreenCategories.Large, ScreenSizeCompareModes.SmallerOrEqualsTo));
```

In this code, replace `DIAGONAL_SIZE_HERE ` with the actual value for your device.

Cheers

**Comment by gabsamples6** [comment]
thanks again for your extremely quick response!!

**Comment by carolzbnbr** [comment]
Yes, sure, go ahead! 

The code is under Licença Apache 2.0.

:D
