### ISSUE TITLE
Suggestion - Maui Removal of throwing exception and return an enum or a result

### ISSUE THREAD

**Issue by gabsamples6** [carolzbnbr/OnScreenSizeMarkup#16]
Given the issue we faced in the Xamarin version , would you consider removing throwing exceptions when ScreenCategories.Not set and returning either a default value or just not set  in the Maui version

Also removing throwing exceptions whenever possible as those will just crash the app or even prevent the app from loading, your control is used in many styles that run at the very beginning of the app and an error will prevent the app from running.

As you know very well google api its not correct all the time and new devices like oppo have difference measures and we cannot possibly prevent  all the issues and add mapping to all possible sizes, so in my view returning a default value is better than the app crashing, 
thanks again

**Comment by carolzbnbr** [comment]
Hi,

On Xamarin library, you could implement your own Fallbackhandler to always return Large if not handled by its parent class:

```csharp
public class MyCustomCategoryFallbackHandler : DefaultCategoryFallbackHandler
    {

        public override bool TryGetCategoryByPhysicalSize(double deviceWidth, double deviceHeight, out ScreenCategories category)
        {
            var result = base.TryGetCategoryByPhysicalSize(deviceWidth, deviceHeight, out category);

            if (result)
            {
                return result;
            }

            category = ScreenCategories.Large;
            return true;  
        }
    }

```

And on your App.cs's constructor, you could do this before the InitializeComponent :

```csharp
  Manager.Current.Handler = new MyCustomCategoryFallbackHandler();
```



On .NET MAUI you could do this on your App.cs:

```csharp


OnScreenSizeMarkup.Maui.Manager.Current.Mappings.Add(new SizeMappingInfo(double.MaxValue, ScreenCategories.Large, ScreenSizeCompareModes.SmallerOrEqualsTo));

```

In this case the library will always assume Large as a fallback.

**Comment by gabsamples6** [comment]
Thanks for the suggestions and I will do that , but  I do think it will be good if the library did not throw exceptions as if not handled it will just crash the app.
