### ISSUE TITLE
Custom Category fallback handlers

### ISSUE THREAD

**Issue by jqueiroz1** [carolzbnbr/OnScreenSizeMarkup#5]
I'm not sure if it a bug but I created a custom handler and I added the line 
  OnScreenSizeMarkup.Core.Manager.Current.Handler = new MyNewFallBackHandlerClass(); 
 to my App.cs file but my code never gets called and the category is still the one created by the default handler.
 Do I need to add it to some where else or call something to do the categorization again with my new handler
If i manually call the TryGetCategoryByPhysicalSize function after i set the new instance then it call my code but the category is never updated.

**Comment by carolzbnbr** [comment]
Hi @jqueiroz1,

I'm assuming you are talking about Xamarin, not Maui, because MAUI has many break changes which I didn't have time to update the documentation.

In order for your custom handler to get called, you must set it before any navigation call is made on your app.cs, otherwise it will fail.

If you are doing that, it would be great if you could send me a demo project, so I can try reproduce it here.

**Comment by jqueiroz1** [comment]
Yes sorry i am using Xamarin and MVVMCROSS. It is add before any navigation. 
So the reason i need a custom handler is because my app is always on landscape which flips the width and height. so i copied the default handler and just swapped the width and height. i will try to get a demo project for you if i can

**Comment by jqueiroz1** [comment]
i managed to fix it. I had to move the call to before the InitializeComponent()
before fix
public partial class App : Application
    {
        public App()
        {
            
            InitializeComponent();
            OnScreenSizeMarkup.Core.Manager.Current.Handler = new HorizontalCategoryFallbackHandler();

           
        }
    }
after fix
public partial class App : Application
    {
        public App()
        {
            OnScreenSizeMarkup.Core.Manager.Current.Handler = new HorizontalCategoryFallbackHandler();
            InitializeComponent();
           
        }
    }

Now it is calling my Custom Handler. Thanks for the help and great work really great NuGet to have.
