### ISSUE TITLE
Using StaticResource causes an invalid exception

### ISSUE THREAD

**Issue by developer9969** [carolzbnbr/OnScreenSizeMarkup#8]
Hi 
This is a brilliant nuget!!!
I am sure its working as designed but using on existing app when lots of values that are defined  int the App.Xaml.

if you have something like this in your App.Xaml

      <OnPlatform
              x:Key="LargeSize"
              x:TypeArguments="x:Double"
              Android="18"
              iOS="20" />

and then  you try to do this

    FontSize="{markups:OnScreenSize 
                            Small='{StaticResource SmallSize}',
                            Medium='{StaticResource DefaultSize}', 
                            Large='{StaticResource LargeSize}'}" 

Than it will crash with a cast exception.

Is there a way that  it could possibly handle a value defined in the app.xaml as a static resource?

Many thanks

**Comment by developer9969** [comment]
found a workaround  - use your onscreesize inside app.xaml

**Comment by carolzbnbr** [comment]
Hi,glad you find a workaround, but I possibly investigate this issue further later anyway to come up with an actual fix. 

Thanks for posting.
