### ISSUE TITLE
Using Markup.OnScreenSize in Code Behind with .net maui?

### ISSUE THREAD

**Issue by nn00xx** [carolzbnbr/OnScreenSizeMarkup#9]
I wanted to use  Markup.OnScreenSize in my Code behind with .net maui but it isnt working.
I guess this feature isnt implemented in .net maui NuGet Package? 
Or is the imlementation different than shown in the example?

**Comment by carolzbnbr** [comment]
Hi, 

Yes. There is a nuget for maui please see https://www.nuget.org/packages/OnScreenSizeMarkup.Maui 

😜

**Comment by userlessworld** [comment]
Hi,

The Problem is I installed the maui nuget but the feature doesnt work. 
I added a Screenshot. In my xamarin project (with xamarin nuget package) the code is working fine. 

[https://paste.pics/d915508bc37a8fd78f4741a43773f738](url)

**Comment by carolzbnbr** [comment]
Hi again,

Using the [Maui Nuget](https://www.nuget.org/packages/OnScreenSizeMarkup.Maui) I sent before, try this:

```csharp
            using OnScreenSizeMarkup.Maui.Helpers;
...
            Grid grid = new Grid
            {
                RowDefinitions =
                {
                    //first row
                    OnScreenSizeHelpers.OnScreenSize(defaultSize: new RowDefinition { Height = new GridLength(100) },
                        large: new RowDefinition { Height = new GridLength(200) },
                        extraLarge: new RowDefinition { Height = new GridLength(300) }
                    ),
                    //second row
                    new RowDefinition(),
                    //third row
                    OnScreenSizeHelpers.OnScreenSize(defaultSize: new RowDefinition { Height = new GridLength(100) },
                        large: new RowDefinition { Height = new GridLength(200) },
                        extraLarge: new RowDefinition { Height = new GridLength(300) }
                    ),
                }
            };
```

**Comment by carolzbnbr** [comment]
HI again,

Just complimenting the previous answer, the latest of the nuget for MAUI had some minor adjustments due to the move to MAUI Community Toolkit that soon might occur.

While that move doesn't happen, I need to find a free spot for creating documentation a specific for MAUI.
